### ISSUE TITLE
snakemake version

### ISSUE THREAD

**Issue by moniekvanselst** [LUMC/HAMLET#1]
since the creation of HAMLET Snakemake has been updated. In this new version 'count' has become a key word, but 'count' is used as a variable in HAMLET. 
Version 5.14 works for me and version 5.18 does not. You should update your readme or change the variable name.

**Comment by Redmar-van-den-Berg** [comment]
I've added a line to the readme to clarify that Snakemake should be installed using the `environment.yml` file to make sure users install a supported version of Snakemake
