### ISSUE TITLE
Problem detecting Singularity

### ISSUE THREAD

**Issue by rschauner** [LUMC/HAMLET#12]
I activated the conda enviorment and built singulairty from the GitHub on MacOS 10.15.7 successfully.

Output from `singularity version`: `3.7.3+125-g9434baf17`

When I run the first test (`pytest --kwd --tag sanity`), it fails because the output does not contain "singularity version 3." Keeping the output this is one of the files.

```
cat /var/folders/fn/0ljsn56d78dbw6nlm5ly7fbxtm2f76/T/pytest_workflow_5jbmvtid/test-qc-sanity-singularity/log.out
singularity-ce version 3.7.3+125-g9434baf17 
```
Is there any recommendation for solving this? It seems like its just a testing issue, but I don't know if there is something different with this version of singularity.

**Comment by Redmar-van-den-Berg** [comment]
I've made an update to the code checking the singularity version [here](https://github.com/LUMC/HAMLET/tree/issue-12), can you give this branch a try?

I don't expect any issues using that version of singularity, although HAMLET hasn't been tested on MacOS at all, so I'll be interested to know how it works for you.

**Comment by Redmar-van-den-Berg** [comment]
Thanks for checking this fix, I've merged the changes.

The tests data itself is actually part of HAMLET and quite small, but the reference files that HAMLET uses are indeed very large (100+GB, since they include the human reference genome indexed for many different tools).
