### ISSUE TITLE
pytest functional failing

### ISSUE THREAD

**Issue by rschauner** [LUMC/HAMLET#15]
I've been trying to set up HAMLET on MacOS and RedHat but have been getting errors on both systems that some files cannot be found. I double checked these and they are included in the HAMLET directory. 
[fun.out.txt](https://github.com/LUMC/HAMLET/files/6655985/fun.out.txt)
[redhat.out.txt](https://github.com/LUMC/HAMLET/files/6656047/redhat.out.txt)

So I tried the frankenstein test on MacOS:
```
snakemake -rp --snakefile Snakefile --configfile test/data/config/test-hamlet-frankenstein.config --use-singularity
Multiple include of /Users/schaunr/software/HAMLET/includes/qc-seq/Snakefile ignored
Multiple include of /Users/schaunr/software/HAMLET/includes/qc-seq/Snakefile ignored
Multiple include of /Users/schaunr/software/HAMLET/includes/qc-seq/Snakefile ignored
Multiple include of /Users/schaunr/software/HAMLET/includes/snv-indels/Snakefile ignored
Multiple include of /Users/schaunr/software/HAMLET/includes/qc-seq/Snakefile ignored
localrules directive specifies rules that are not present in the Snakefile:
        plot_sfstar_fusion_cp

Building DAG of jobs...
MissingInputException in line 50 of /Users/schaunr/software/HAMLET/includes/snv-indels/Snakefile:
Missing input files for rule align_vars:
/Users/schaunr/software/exports/sasc-testing/fixtures/HAMLET/deps/data/gmap-genome-index/GCA_000001405.15_GRCh38_no_alt_analysis_set
```
What am I missing?

**Comment by Redmar-van-den-Berg** [comment]
Can you verify that the reference file is indeed located on `/Users/schaunr/software/exports/sasc-testing/fixtures/HAMLET/deps/data/gmap-genome-index/GCA_000001405.15_GRCh38_no_alt_analysis_set` on your system? Otherwise, you will have to update the configuration file of the test to make sure it points to the correct folder.
