### ISSUE TITLE
rose-dt

### ISSUE THREAD

**Issue by ZunsongHu** [LUMC/HAMLET#16]
Hi,
I followed your installation process using the environment.yml. I'm trying to run the ITD snakemake file. But I found the executable rose-dt was missing. Where can I install this?
Thanks a lot!

**Comment by Redmar-van-den-Berg** [comment]
HAMLET requires singularity to run, which automatically downloads all required tools, including rose-dt. See the [documentation](https://github.com/LUMC/HAMLET#example-command) for details.
