### ISSUE TITLE
Errors - pytest functional 

### ISSUE THREAD

**Issue by Luna0308** [LUMC/HAMLET#18]
Hi Redmar,
I think I have successfully installed Hamlet. Pytest sanity and pytest dry-run ' passed successfully without any errors, but I am getting 32 errors in pytest functional. I searched but could not find why I am getting the errors. I added the error logs. Thank you in advance for your help.
[pytest_functional_test-qc-duo_log.err.txt](https://github.com/LUMC/HAMLET/files/7982592/pytest_functional_test-qc-duo_log.err.txt)
[pytest_functional_test-qc-single-low-qual-adapters_log.err.txt](https://github.com/LUMC/HAMLET/files/7982593/pytest_functional_test-qc-single-low-qual-adapters_log.err.txt)
[pytest_functional_test-qc-trio_log.err.txt](https://github.com/LUMC/HAMLET/files/7982594/pytest_functional_test-qc-trio_log.err.txt)
.

**Comment by Luna0308** [comment]
Now it works. Thanks.

**Comment by Luna0308** [comment]
Hi Redmar,
Me again :).  pytest functional passed without any errors, but this time pytest integration also gave some errors. I tried but could not find the reason. I added the error logs. Thank you for your help.
[pytest_integration_log.err.txt](https://github.com/LUMC/HAMLET/files/8008743/pytest_integration_log.err.txt)

**Comment by Redmar-van-den-Berg** [comment]
It looks like a similar problem, the test folder is not available inside the singularity container:
`cutadapt: error: [Errno 2] No such file or directory: 'test/data/fastq/SRR8615630_MECOM_HMBS_1.fastq.gz'`

Which command are you using to run the test? If the pipeline itself is available, then the test folder should also be.
As a workaround, you can try to add the following snakemake flag to all tests tagged with `integration`:
```
--singularity-args ' --bind /home'
```

**Comment by Luna0308** [comment]
It works, thanks again !
