### ISSUE TITLE
Error: Invalid value: Unexpected column names

### ISSUE THREAD

**Issue by moniekvanselst** [LUMC/HAMLET#2]
While running HAMLET with a smal sample it did not find any fusions with fusioncatcher, when this happens the last column "Predicted_effect" is not made in the output. This causes plot_fc to have an "Error: Invalid value: Unexpected column names" error. 

After manually adding the column name it worked again, only to give a "null division error" in intersect_fusions.  

I copied both errors in the attached files
[plot_fc_ERROR.txt](https://github.com/LUMC/HAMLET/files/4737554/plot_fc_ERROR.txt)
[intersect_fusions_ERROR.txt](https://github.com/LUMC/HAMLET/files/4737557/intersect_fusions_ERROR.txt)

**Comment by Redmar-van-den-Berg** [comment]
Can you share a minimum fastq dataset (preferably) or set of inputs for fusioncatcher that can be used to replicate this issue?

**Comment by moniekvanselst** [comment]
The samples are still to big to be uploaded, so i put them here: https://drive.google.com/drive/folders/1icByNwdAaiTy1r5os3Fb3J6-BbULPSAN?usp=sharing

note: sample NOMO1-16714 also has the error that is descriped in issue 3

**Comment by Redmar-van-den-Berg** [comment]
Thanks for the data, I will have a look. Do you mind if I add the data from NOMO1-16714 to the tests data for HAMLET? That way we can make sure that these issues do not show up in later versions of HAMLET

**Comment by moniekvanselst** [comment]
You cam use all of the samples for as test data if you want.

**Comment by Redmar-van-den-Berg** [comment]
This bug has been fixed upstream, I'm waiting for a new release of the tool in question to include it in HAMLET: https://github.com/bow/crimson/pull/12

**Comment by Redmar-van-den-Berg** [comment]
This has been fixed in the devel branch (See 9a46725)
