### ISSUE TITLE
Error: not enough memory for BAM sorting

### ISSUE THREAD

**Issue by XLIU-hub** [LUMC/HAMLET#30]
Hi,
An error occurs for BAM sorting, STAR indicates 47G ram memory. 

Max memory needed for sorting = 45988878036
EXITING because of fatal ERROR: not enough memory for BAM sorting: 
SOLUTION: re-run STAR with at least --limitBAMsortRAM 46988878036

Logfile:
[Log.log.txt](https://github.com/LUMC/HAMLET/files/13961364/Log.log.txt)

**Comment by Redmar-van-den-Berg** [comment]
This issue on STAR could be related, it looks like STAR doesn't handle sorting very well if the input is already sorted by coordinate. https://github.com/alexdobin/STAR/issues/289

**Comment by Redmar-van-den-Berg** [comment]
We should probably switch to using samtools to sort the output, instead of having STAR create the bam file. This will also allow us to determine the output filename.

We can use an existing multi-package-container for STAR and samtools:
```bash
hash=$(mulled-hash star=2.7.10b,samtools=1.16.1,gawk=5.1.0 --hash v2)
url="docker://quay.io/biocontainers/${hash}-0"
echo $url
docker://quay.io/biocontainers/mulled-v2-1fa26d1ce03c295fe2fdcf85831a92fbcbd7e8c2:a53b7c56addcc8233531e25d69b320bc56964994-0
```

**Comment by Redmar-van-den-Berg** [comment]
@XLIU-hub Is this still a problem or can this issue be closed?

**Comment by XLIU-hub** [comment]
Did not run into this issue in the diagnostic samples. Probably STAR estimate to memory usage pretty high if the sample is sorted.
