### ISSUE TITLE
Hamlet crashes when generating large size pdf report

### ISSUE THREAD

**Issue by XLIU-hub** [LUMC/HAMLET#36]
In some cases with over ~30 images in the report. Python package pdfkit and its dependency wkhtmltopdf cannot properly generate a pdf report.

**Comment by Redmar-van-den-Berg** [comment]
This error could not be reproduced. In cases where HAMLET fails on the report generation, please attempt to re-run the pipeline, which should resume the pipeline where it left of and generate the PDF report.
