### ISSUE TITLE
star-fusion setup

### ISSUE THREAD

**Issue by mathieuq** [LUMC/HAMLET#4]
Stand-alone star-fusion requires a large file download and a preferred singularity version to run. Does HAMLET require full stand-alone installation of star-fusion and, in which case, do we need to worry about the version of singularity installed by HAMLET? Is there a way to avoid installing a full version star-fusion and related files while still retaining HAMLET functionality?

**Comment by Redmar-van-den-Berg** [comment]
All required input files are part of the data download that is linked on the readme page, I haven't investigated if there is a way to reduce the size of the required reference files.

I'm not sure what you mean with the version of singularity for star-fusion, that should not be relevant as long as the version of singularity is recent enough. For reference, version v1.0.0 of HAMLET was clinically validated and runs using singularity 3.5.3 with bioconda star-fusion version 1.6.0
