### ISSUE TITLE
required tool 'rose-dt' seems to be only in a private repository

### ISSUE THREAD

**Issue by pjewell-biociphers** [LUMC/HAMLET#6]
Good day, 

I am in the process of working through a number of installation obstacles to run the full workflow for HAMLET. 

I have gotten to a point of needing the tool called "rose-dt" to be available in the path. Information is scarce. I found a reference to it on your repository: https://git.lumc.nl/hem/hamlet/commit/a71d301bbdd363018df132cae94ca8cc7b68026a -- However, the link that it points to: https://git.lumc.nl/hem/rose-dt  ; seems to be a private repository (I am asked to log in to view it). 

Can you please provide instructions on where users should go do download and install the 'rose-dt' tool, which is a prerequisite for HAMLET ?

Thanks, 
-Paul

**Comment by Redmar-van-den-Berg** [comment]
There should not be any need to install further tools once you have installed singularity, and the HAMLET conda environment as specified in the readme. HAMLET has been developed to run using docker/singularity containers, which will be downloaded automatically at the start of the analysis.
This way, I can update any of the tools to a later version, and all users can start using the new tool immediately, without having to manually re-install a later version on their system.

In case you still want to install rose-dt manually, I've made the rose-dt repository public.

**Comment by Redmar-van-den-Berg** [comment]
Hi Paul,

You also need to specify the `--use-singularity` flag for snakemake, I see that I forgot to add that to the readme. Thank you for your questions and feedback, they really help me improve the documentation.
