### ISSUE TITLE
Various runtime errors / Installation guidance 

### ISSUE THREAD

**Issue by pjewell-biociphers** [LUMC/HAMLET#7]
Good day again, 

I have been working to try to install and run this software on a few different environments without full success yet. There are enough strange issues that I thought it would be relevant to ask. 

Most recent system I am trying with is running ubuntu 18.04. 

Before going into the specifics, I wanted to mention that in a previous closed issue, it was suggested that singularity images should be able to be used for the majority of the programs run by hamlet. Thus far, I have been trying to install each of the dependencies manually. However, it would be much easier if all of the software could be run in singularity. As I have now start working with a machine where I have admin access, I should be able to do this. Are there instructions for using singularity running dependencies?

Now on to the specific issues I have so far. From your readme I have the sanity and dry run tests passing with all success. 

Integration does not pass (155 failed, 1 pass) -- I get a lot of "ERROR  : Failed to set effective UID to 0" -- does this software require root access to run? (I can attach the full log if that would be helpful)

From a run of the frankenstein example modified run (attaching config file), with $ snakemake -s Snakefile  --configfile test2.config   ;; I don't get singularity errors at all, the run appears to try to use locally installed software instead. I am to the point of getting some error that CIRCOS was called incorrectly, and also a divide by zero error in running hist2count.py. As I was starting to become a little less confident in debugging, I thought I would ask for your thoughts here. 

Thank you for whatever time you have to help assist us with running your software. I am sure that based on the time I have taken, there should be an easier way somewhere I am missing! Please let me know what other information I could provide to help debug. 

[snakemake_outer_log.txt](https://github.com/LUMC/HAMLET/files/5008283/snakemake_outer_log.txt)
[functional_test_results.txt](https://github.com/LUMC/HAMLET/files/5008294/functional_test_results.txt)
[test2.config.txt](https://github.com/LUMC/HAMLET/files/5008298/test2.config.txt)

**Comment by Redmar-van-den-Berg** [comment]
Every tool that is used by HAMLET is available automatically via singularity, so there is no need to install any of them locally. In fact, using HAMLET with singularity images is currently the only supported way to use HAMLET, since it is such a hassle to manually install all the required tools.

Because of this, HAMLET does not require root access to run, so I'm confused about the ERROR message you posted.

Can you test if you can run an image with singularity directly? From the [singularity documentation](https://singularity.lbl.gov/quickstart):
```bash
$ singularity run shub://vsoch/hello-world
 59.75 MiB / 59.75 MiB [===========================================================================] 100.00% 42.41 MiB/s 1s
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
RaawwWWWWWRRRR!! Avocado!
```

It looks like your test of the frankenstein sample did not include the --use-singularity flag that is present in the test command. To make use of singularity, you have to specify the `--use-singularity` flag to Snakemake.

Can you run the frankenstein sample again with the following command and post the output here?
```bash
snakemake -rp --snakefile Snakefile --configfile test2.config.txt --verbose --use-singularity
```

**Comment by pjewell-biociphers** [comment]
Hello @Redmar-van-den-Berg ,

Thank you very much for taking the time to respond to my issue. Coming to this from outside, I do miss some things by default. Before getting into the details, it might make some sense to point out that you mentioned that using the singularity images is the only supported method of running the software, but this switch (--use-singularity) is not mentioned anywhere in the hamlet README file. For newcomers to this environment of software, it could help to have this information (use --use-singularity switch) pointed out explicitly in the "execution" section of the readme or other relevant documentation. 

The first issue was still " Failed to set effective UID to 0" -- it seems that after activating the conda ENV, there was a version of singularity installed locally, which of course does not set the setuid bit. I'm not to go about setting this up on a shared HPC, but for now on a development system I can install a singularity system package, and point the ~/miniconda3/envs/HAMLET/bin/singularity to the system one with a symlink. Then, I am able to run singularity with the command you specified above successfully. 

There were a couple of other issues related to the singularity bind path and such, but I have worked through them for now. I also got an error in the run, but I could not find it in the log, and then I ran the same command a second time and all steps succeeded. Unnerving but I don't expect to be able to debug it right now. 

I will discuss the outputs with the end user and get back to you if we have additional questions. Again, thanks for helping out someone new to this pipeline!

-Paul

**Comment by Redmar-van-den-Berg** [comment]
Hi @pjewell-biociphers,

I've added the use of the `--use-singularity` flag to the readme, and also added an explicit example of running one of the tests manually using the `--use-singularity` flag.

I have had some issues using singularity on older versions of Ubuntu where I got random failures when Snakemake tried to start too many containers in a short amount of time, and some resource limit for /dev/loop devices was encountered. You might want to install the latest version of singularity manually if this problem keeps occurring.

I'm glad you find this pipeline useful, hopefully you won't run into any more issue. If you do, please do not hesitate to ask.
