### ISSUE TITLE
Single-end data

### ISSUE THREAD

**Issue by mathieuq** [LUMC/HAMLET#8]
Hi Redmar,

Will HAMLET run on single-end data and, if so, what would be the proper way to refer to single-end samples in the config file?

Thank you

**Comment by Redmar-van-den-Berg** [comment]
Running HAMLET on single-end data is not something that is currently supported.

Having said that, I've had a quick look and it looks like all tools that work with the raw fastq files have support for single-end data as well, so it should be possible to add this. I'd be happy to accept a merge request for this functionality if you are able to add it.
